---
- name: provide information about local host
  debug:
    msg:
#    - "Everything: {{ hostvars[inventory_hostname] }}"
    - "IP address: {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    - "Hostname: {{ hostvars[inventory_hostname]['ansible_env']['HOSTNAME'] }}"
    - "Ansible connection: {{ hostvars[inventory_hostname]['ansible_connection'] }}"
    - "Distribution: {{ hostvars[inventory_hostname]['ansible_distribution'] }} {{ hostvars[inventory_hostname]['ansible_distribution_version'] }}"
- name: install ddupdate package
  package:
    name: ddupdate
    state: present
- name: configure ddupdate
  debug:
    msg: "Please run the command ddupdate-config to configure ddupdate for your DynDNS environment."
- name: configure ddupdate to work with NetworkManager
  command: cp /usr/share/ddupdate/dispatcher.d/50-ddupdate /etc/NetworkManager/dispatcher.d/
- name: configure cron to run ddupdate every 10 minutes
  template:
    src: "etc/cron.d/ddupdate.j2"
    dest: "/etc/cron.d/ddupdate"
